/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import React, { useRef } from 'react'

export default function Model(props) {
  const group = useRef()
  const mesh = useRef()
  const { nodes } = useGLTF('/eye.gltf')

  useFrame(({ delta, clock }) => {
    const g = mesh.current

    g.rotation.x += 0.01
    g.rotation.x += 0.01
    g.rotation.z += 0.01
  })

  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        ref={mesh}
        castShadow
        receiveShadow
        geometry={nodes.Icosahedron.geometry}
        // material={nodes.Icosahedron.material}
      >
        <meshStandardMaterial color={'#ff8426'} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/eye.gltf')
