/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, OrthographicCamera } from "@react-three/drei";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/cube.gltf");
  return (
    <group ref={group} {...props} dispose={null}>
      <OrthographicCamera
        makeDefault={false}
        far={50000}
        near={-50000}
        position={[378, 179, 1000]}
        rotation={[0, 0, 0]}
      >
        <directionalLight
          intensity={0.8}
          decay={2}
          position={[850000, 1300000, 1000000]}
          rotation={[-0.9, 0.5, -0.3]}
        />
      </OrthographicCamera>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={nodes.Cube.material}
      />
    </group>
  );
}

useGLTF.preload("/cube.gltf");
